### ISSUE TITLE
toolbox的gram_vec函数问题

### ISSUE THREAD

**Issue by BoatingZeng** [yanshao9798/segmenter#1]
```
        ngram = 0
        for k in dic.keys():
            if '<PAD>' not in k:
                ngram = len(k)
                break
```

上面的这段代码中，查看dic的前三个keys分别是`<P>、<UNK>、<#>`，所以这里必然`ngram = len('<P>') = 3`。我猜这里原本应该是用ngram文件里的字符来判断这个n是多少。所以判断条件是否应该改成这样？

```
if '<PAD>' not in k and k not in ['<P>', '<UNK>', '<#>']:
```

**Comment by yanshao9798** [comment]
这段代码确实是用ngram文件里的字符来判断这个n是多少。但是当你用dic.keys()来调用字典key的时候，前三个keys其实并不是<P>、<UNK>、<#>。因为python里面为了使字典检索更有效率，字典的key默认是有序的。

**Comment by BoatingZeng** [comment]
哦，我把代码转成python3了，所以排在前面的是这三个键。谢谢。
