### ISSUE TITLE
transducer相关的部分是用来做什么的？

### ISSUE THREAD

**Issue by BoatingZeng** [yanshao9798/segmenter#2]
我用的数据格式是(空格分割)：
`迈向  充满  希望  的  新  世纪  ——  一九九八年  新年  讲话  （  附  图片  １  张  ）  `
生成出来的dict.txt永远是空的（看代码猜测这个跟transducer有关）。transducer我感觉好像是跟翻译有关，但是我在数据里添加中英混合的句子，也触发不了transducer部分的代码。那么transducer和dict.txt在什么情况下会用到？我只研究中文相关部分。谢谢。

**Comment by yanshao9798** [comment]
transducer和dict.txt是在处理Universal Dependencies中的multi-word token时会用到。如果只处理中文，那它们就不会用到。

**Comment by BoatingZeng** [comment]
好的，谢谢。
